version: '3.8'
services:
  app:
    build:
      context: .
      target: builder
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c 'yarn install && yarn run dev'

volumes:
  node_modules: